# Generated by Django 3.1.3 on 2021-01-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_date', models.DateField(auto_now=True)),
                ('name', models.TextField()),
                ('list', models.TextField()),
            ],
        ),
    ]
