# Generated by Django 3.1.3 on 2021-01-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plextvstation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlists',
            name='user',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='savedlists',
            name='list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='savedlists',
            name='name',
            field=models.TextField(default=None),
        ),
    ]
